### ISSUE TITLE
Add current loop size display to deck overview

### ISSUE THREAD

**Issue by RonnieTiger** [timewasternl/Pioneered#20]
I feel that this skin is missing a small display to show what the current loop length is set to. e.g 1/4 - 4 8 16 etc. this could fit nicely in the bottom deck overview screens where there's lots of empty space around the tempo display area! this is incluided in the default skin, 

I think it would fit nicely either after the TIME text to the right, or to the left of the tempo reading, whatever you feel is the most pleasing/practical to implement. 

Nothing mega fancy, simply a bit of text that says 
loop/jump
[ value ]

**Comment by bvobart** [comment]
Oeehh that's a good idea, thanks! I'd be happy to implement it if I find the time to work on Pioneered again :+1: In the mean time, feel free to give it a shot :P

**Comment by RonnieTiger** [comment]
> Oeehh that's a good idea, thanks! I'd be happy to implement it if I find the time to work on Pioneered again 👍 In the mean time, feel free to give it a shot :P

would love to, but I have Zero experience making skins for Mixxx, Even though it's all QT/XML based I don't even know where to begin, what the variable names would be or how to add them. I'm a total noob in this regard. 
I did have a crack at it though, but I can't figure out how to add the needed information cleanly or what variable to even access, or how to display said variable.

**Comment by GorgiAstro** [comment]
I opened a PR for an implementation proposal of a loop size indicator: https://github.com/timewasternl/Pioneered/pull/22

**Comment by bvobart** [comment]
Thanks for your implementation @GorgiAstro, it's been merged! :rocket:
