### ISSUE TITLE
Touching the waveform prevents playing on the deck again

### ISSUE THREAD

**Issue by GorgiAstro** [timewasternl/Pioneered#21]
How to reproduce:

* Needs Mixxx and Pioneered with a Raspberry Pi 7" Touchscreen
* Play a song on one of the decks
* Touch the deck waveform area on the touchscreen

Expected behaviour: it makes the cursor move a little bit and then it stops playing, whereas the play button is still lit. Then nothing can make this deck continue playing, I tried everything I could find (play/pause, changing song, CUEing, going back to the beginning of the song), that won't make the cursor move anymore, it requires restarting mixxx.

I use https://github.com/fayaaz/mixxx-pi-gen on my RPi, it has the latest version of the Pioneered skin, and Mixxx 2.4.0.

Edit: I tried with the mouse, clicking on the deck waveform works as expected, it stops playing and then upon releasing the mouse the deck restarts playing.

**Comment by bvobart** [comment]
Hmmmmm that's strange, I don't think I've ever experienced something like that before. Are you sure it's a bug in the skin or do you think it's rather a bug in Mixxx? Do you only get it with Pioneered or can you reproduce it on other skins with the same waveform display?

**Comment by GorgiAstro** [comment]
Oh indeed my bad, the problem also occurs with other skins. I will investigate more and maybe open an issue in the mixxx github.
